name: ev_platform

packages:
  - apps/*
  - packages/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- flutter analyze --fatal-infos
    description: Analyze all packages

  test:
    run: melos exec --dir-exists=test -- flutter test --coverage
    description: Run all tests

  format:
    run: melos exec -- dart format --set-exit-if-changed .
    description: Check formatting

  gen:
    run: melos exec --dir-exists=lib/src/l10n -- flutter gen-l10n
    description: Generate localization files

  build:runner:
    run: melos exec --depends-on=build_runner -- dart run build_runner build --delete-conflicting-outputs
    description: Run code generation

  clean:
    run: melos exec -- flutter clean
    description: Clean all packages
